// src/components/Header.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { Radio } from 'lucide-react';

const Header = () => {
  return (
    <header className="glass" style={{ 
      position: 'sticky', 
      top: '1rem', 
      margin: '1rem auto', 
      width: 'max-content',
      maxWidth: 'min(90%, 1200px)',
      padding: '0.75rem 2rem',
      zIndex: 1000,
      display: 'flex',
      alignItems: 'center',
      gap: '3rem',
      justifyContent: 'center'
    }}>
      <div className="logo d-flex align-items-center" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 700, fontSize: '1.25rem' }}>
        <Radio className="text-accent" aria-hidden="true" size={24} />
        <span className="text-gradient">FootCast</span>
      </div>
      
      <nav aria-label="Navegación principal">
        <ul style={{ 
          listStyle: 'none', 
          display: 'flex', 
          gap: '2rem',
          margin: 0,
          padding: 0
        }}>
          <li>
            <NavLink 
              to="/" 
              className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}
              style={navLinkStyle}
            >
              Inicio
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/episodios" 
              className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}
              style={navLinkStyle}
            >
              Episodios
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/contacto" 
              className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}
              style={navLinkStyle}
            >
              Contacto
            </NavLink>
          </li>
        </ul>
      </nav>

      <style>{`
        .nav-link {
          font-weight: 500;
          color: var(--color-text-muted);
          position: relative;
          padding: 0.5rem 0;
        }
        .nav-link:hover, .nav-link:focus {
          color: var(--color-text);
        }
        .nav-link.active {
          color: var(--color-text);
        }
        .nav-link.active::after {
          content: '';
          position: absolute;
          bottom: 0;
          left: 0;
          width: 100%;
          height: 2px;
          background: var(--color-accent);
          border-radius: 2px;
        }
      `}</style>
    </header>
  );
};

const navLinkStyle = {
  textDecoration: 'none',
  fontSize: '1rem',
  transition: 'var(--transition-smooth)'
};

export default Header;

// src/components/header.vue
<template>
  <nav class="navbar navbar-expand-lg sticky-top shadow-sm custom-header">
    <div class="container-fluid px-lg-5">
      <a class="navbar-brand logo fw-bold fs-3 text-white" href="#">
        Foot<span class="text-accent">Cast</span>
      </a>
      <button class="navbar-toggler border-0 text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="navbar-nav ms-auto gap-3">
          <router-link to="/" class="nav-link text-white-50 px-3 py-2 rounded custom-nav-btn" active-class="text-white fw-bold">Inicio</router-link>
          <router-link to="/episodios" class="nav-link text-white-50 px-3 py-2 rounded custom-nav-btn" active-class="text-white fw-bold">Episodios</router-link>
          <router-link to="/contacto" class="nav-link text-white-50 px-3 py-2 rounded custom-nav-btn" active-class="text-white fw-bold">Contacto</router-link>
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Header',
  emits: ['change-view']
}

</script>

<style scoped>
.custom-header {
  background-color: #1a2347;
  height: 80px;
}

.text-accent {
  color: #4f46e5;
}

.custom-nav-btn {
  font-size: 15px;
  font-weight: 500;
  transition: all 0.3s ease;
}

.custom-nav-btn:hover {
  color: white !important;
  background-color: rgba(255, 255, 255, 0.05);
}

@media (max-width: 991.98px) {
  .custom-header {
    height: auto;
  }
}
</style>
